### Sign up

POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "email": "basit@gmail.com",
    "fullName": "Abdulraheem Abdulbasit",
    "password": "qwerty"
}


### Sign in
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
    "email": "basit@gmail.com"
}



### Send message

POST http://localhost:3000/messages
Content-Type: application/json

{
    "senderId": 1,
    "receiverId": 3,
    "text": "Glad to hear"
}


### Get chat messages
GET  http://localhost:3000/messages
Content-Type: application/json

{
    "senderId": 1,
    "receiverId": 2
}