### Sign up

POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "email": "basit@gmail.com",
    "fullName": "Abdulraheem Abdulbasit",
    "password": "qwerty"
}


### Sign in
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
    "email": "basit@gmail.com"
}



### Send message

POST http://localhost:8000/messages
Content-Type: application/json

{
    "senderId": "2ba73fbb-4483-4ae6-9f43-df85c6a00a7d",
    "receiverId": "a29f2fbc-cfe0-40d3-be50-7dbda57b5994",
    "text": "Good"
}


### Get chat messages
GET  http://localhost:8000/messages/2ba73fbb-4483-4ae6-9f43-df85c6a00a7d/chat/a29f2fbc-cfe0-40d3-be50-7dbda57b5994
